
services:
  - type: web
    name: weather-chatbot-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: API_KEY
        value: your_openweathermap_api_key_here
